SELECT A.DIV_CD AS CMPNY_CD
      ,A.DIV_CD AS RS_DIV_CD
      ,DECODE(A.ML_ACCT_CAT_CD, 'NSALES', 'SALE', A.ML_ACCT_CAT_CD) AS KPI_CD
      ,B.PLN_YYYYMM AS BASE_YYYYMM
      ,B.WEEK_NO AS BASE_MMWEEK
      ,A.PLN_YYYYMM AS PLN_YYYYMM
      ,CASE WHEN A.PLN_YYYYMM = B.PLN_YYYYMM THEN 'PR0'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 1), 'YYYYMM') THEN 'PR1'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 2), 'YYYYMM') THEN 'PR2'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 3), 'YYYYMM') THEN 'PR3'
       END AS SCENARIO_TYPE_CD
      ,A.KRW_AMT AS CURRM_KRW_AMT
      ,A.USD_AMT AS CURRM_USD_AMT
      ,TRUNC(A.CREATION_DATE)
      ,'ARES'
      ,TRUNC(A.LAST_UPD_DATE)
      ,'ARES'
FROM   TB_RFE_ML_UPLD_RSLT_S A, TB_RFE_ML_WEEK_M B
WHERE  B.PLN_YYYYMM   IN ( '201511','201512')
AND    A.DATA_TYPE_CD = 'DIV'
AND    A.PLN_YYYYWEEK = B.PLN_YYYYWEEK
AND    B.PLN_YYYYMM   <= A.PLN_YYYYMM
AND    A.PLN_YYYYMM   < TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 4), 'YYYYMM')      
AND    A.KRW_AMT      <> 0;
;


SELECT 'GBU' AS CMPNY_CD
      ,'GBU' AS RS_DIV_CD
      ,DECODE(A.ML_ACCT_CAT_CD, 'NSALES', 'SALE', A.ML_ACCT_CAT_CD) AS KPI_CD
      ,B.PLN_YYYYMM AS BASE_YYYYMM
      ,B.WEEK_NO AS BASE_MMWEEK
      ,A.PLN_YYYYMM AS PLN_YYYYMM
      ,CASE WHEN A.PLN_YYYYMM = B.PLN_YYYYMM THEN 'PR0'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 1), 'YYYYMM') THEN 'PR1'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 2), 'YYYYMM') THEN 'PR2'
            WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 3), 'YYYYMM') THEN 'PR3'
       END AS SCENARIO_TYPE_CD
      ,A.SUBSDR_CD
      ,C.SUBSDR_SHRT_NAME
      ,SUM(A.KRW_AMT) AS CURRM_KRW_AMT
      ,SUM(A.USD_AMT) AS CURRM_USD_AMT
      ,TRUNC(A.CREATION_DATE)
      ,'ARES'
      ,TRUNC(A.LAST_UPD_DATE)
      ,'ARES'
FROM   TB_RFE_ML_UPLD_RSLT_S A
      ,TB_RFE_ML_WEEK_M      B
      ,(
        SELECT DISTINCT S.SUBSDR_SHRT_NAME, S.SUBSDR_CD, S.SUBSDR_KOR_NAME
        FROM TB_CM_SUBSDR_PERIOD_H S
        WHERE S.MGT_TYPE_CD  = 'CM'
        AND   S.ACCTG_YYYYMM = '*'
        AND   S.ACCTG_WEEK   = '*'
        AND   S.TEMP_FLAG    = 'N' ) C
WHERE  B.PLN_YYYYMM   IN ( '201511','201512')
AND    A.DIV_CD       IN ('HE', 'MC', 'HNA', 'VC', 'EBC', 'IC')
AND    A.DATA_TYPE_CD = 'SUBSDR'
AND    A.PLN_YYYYWEEK = B.PLN_YYYYWEEK
AND    B.PLN_YYYYMM   <= A.PLN_YYYYMM
AND    A.PLN_YYYYMM   < TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 4), 'YYYYMM')
AND    A.KRW_AMT      <> 0
AND    C.SUBSDR_CD    = A.SUBSDR_CD(+)
GROUP BY A.ML_ACCT_CAT_CD
        ,B.PLN_YYYYMM 
        ,B.WEEK_NO
        ,A.PLN_YYYYMM 
        ,CASE WHEN A.PLN_YYYYMM = B.PLN_YYYYMM THEN 'PR0'
              WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 1), 'YYYYMM') THEN 'PR1'
              WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 2), 'YYYYMM') THEN 'PR2'
              WHEN A.PLN_YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(B.PLN_YYYYMM, 'YYYYMM'), 3), 'YYYYMM') THEN 'PR3'
         END 
        ,A.SUBSDR_CD
        ,C.SUBSDR_SHRT_NAME
        ,TRUNC(A.CREATION_DATE)
        ,TRUNC(A.LAST_UPD_DATE)
;