-- VDT_L2_1, CLT_L2_2
SELECT *
FROM   IPTDW.IPTDW_RES_DIM_CORP_DISPLAY_MASTER 
WHERE  CODE_TYPE = 'SMR_PROD_MST'
AND    ATTRIBUTE1 = 'CLT_L2_2'


WITH UR
;


UPDATE IPTDW.IPTDW_RES_DIM_CORP_DISPLAY_MASTER
SET    USE_FLAG = 'Y'
      ,ATTRIBUTE2 = 'B2C_DIV'
WHERE  CODE_TYPE = 'SMR_PROD_MST'
AND    ATTRIBUTE1 = 'CLT_L2_2'


WITH UR
;
