SELECT *
FROM   IPTDW.IPTDW_RES_DIM_CORP_DISPLAY_MASTER 
WHERE  CODE_TYPE = 'SMR_PROD_MST'
AND    ATTRIBUTE1 = 'CLT_L1_1'


WITH UR
;


UPDATE IPTDW.IPTDW_RES_DIM_CORP_DISPLAY_MASTER
SET    USE_FLAG = 'Y'
WHERE  CODE_TYPE = 'SMR_PROD_MST'
AND    ATTRIBUTE1 = 'CLT_L1_1'


WITH UR
;
