
-- MASTER INFO / MDL_SFFX_CD, INV_LOCN_TYPE_CD, SCENARIO_TYPE_CD, SUBSDR_CD
SELECT *
FROM   NPT_DW_MGR.TB_DWW_PROD_MD_INV_MONTHLY_H
;

-- MODEL SUFFIX INFO / MDL_SFFX_CD
SELECT *
FROM   NPT_APP.NV_DWD_MDL_PERIOD_H
;

-- DIVISION INFO (DIVISION LEVEL 4까지 구분) / DIV_CD
SELECT *
FROM   NPT_APP.NV_DWD_DIV_LEAF_M
;

-- 재고창고분류 / INV_LOCN_TYPE_CD
SELECT *
FROM   NPT_APP.NV_DWD_INV_LOCN_TYPE_M
;

-- 시나리오타입구분 / SCENARIO_TYPE_CD
SELECT *
FROM   NPT_APP.NV_DWD_SCENARIO_TYPE_M
;

-- SUBSIDIARY MASTER / SUBSDR_CD
SELECT *
FROM   NPT_APP.NV_DWD_SUBSDR_M
;
