INSERT INTO IPTDW.IPTDW_RES_DIM_CORP_DISPLAY_MASTER
(
   CODE_TYPE
  ,DIVISION_CODE
  ,CORPORATION_CODE
  ,DISPLAY_NAME1
  ,DISPLAY_NAME2
  ,DISPLAY_ORDER_SEQ
  ,USE_FLAG
  ,ATTRIBUTE1
  ,CREATION_DATE
  ,CREATE_USER_ID
  ,LAST_UPDATE_DATE
  ,LAST_UPDATE_USER_ID
)
SELECT 'SMR_PROD_MST'
      ,SUBSTR(A.PROD_CD,1,4)
      ,SUBSTR(A.PROD_CD,5,8)
      ,A.PROD_KOR_NM
      ,A.PROD_ENG_NM
      ,A.PROD_SORT_NO
      ,'N'
      ,A.PROD_CD
      ,CURRENT TIMESTAMP
      ,'ares'
      ,CURRENT TIMESTAMP
      ,'ares'
FROM  (
       SELECT DISTINCT ATTRIBUTE17 AS PROD_CD
             ,ATTRIBUTE18 AS PROD_KOR_NM
             ,ATTRIBUTE19 AS PROD_ENG_NM
             ,ATTRIBUTE16 AS PROD_SORT_NO
       FROM   IPTDW.IPTDW_RES_EXCEL_UPLOAD_DATA
       WHERE  SEQ = '1510'
       UNION ALL
       SELECT DISTINCT ATTRIBUTE21
             ,ATTRIBUTE22
             ,ATTRIBUTE23
             ,ATTRIBUTE20
       FROM   IPTDW.IPTDW_RES_EXCEL_UPLOAD_DATA
       WHERE  SEQ = '1510'
       UNION ALL
       SELECT DISTINCT ATTRIBUTE25
             ,ATTRIBUTE26
             ,ATTRIBUTE27
             ,ATTRIBUTE24
       FROM   IPTDW.IPTDW_RES_EXCEL_UPLOAD_DATA
       WHERE  SEQ = '1510'
       UNION ALL
       SELECT DISTINCT ATTRIBUTE29
             ,ATTRIBUTE30
             ,ATTRIBUTE31
             ,ATTRIBUTE28
       FROM   IPTDW.IPTDW_RES_EXCEL_UPLOAD_DATA
       WHERE  SEQ = '1510'
      ) A
  WHERE A.PROD_KOR_NM IS NOT NULL
WITH UR;