INSERT INTO IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY
(
   BASE_YYYYMM
  ,SCENARIO_TYPE_CD
  ,DIV_CD
  ,SUBSDR_CD
  ,AU_CD
  ,MANUAL_ADJ_FLAG
  ,KPI_CD
  ,CAT_CD
  ,SUB_CAT_CD
  ,ZONE_RNR_CD
  ,SUBSDR_RNR_CD
  ,CNTRY_CD
  ,APPLY_YYYYMM
  ,CURRM_KRW_AMT
  ,CURRM_USD_AMT
  ,ACCU_KRW_AMT
  ,ACCU_USD_AMT
  ,ATTRIBUTE1_VALUE
  ,ATTRIBUTE2_VALUE
  ,ATTRIBUTE3_VALUE
  ,ATTRIBUTE4_VALUE
  ,ATTRIBUTE5_VALUE
  ,CREATION_DATE
  ,CREATION_USR_ID
  ,LAST_UPD_DATE
  ,LAST_UPD_USR_ID
)
SELECT A.ATTRIBUTE1  AS BASE_YYYYMM
      ,A.ATTRIBUTE10 AS SCENARIO_TYPE_CD
      ,A.ATTRIBUTE11 AS DIV_CD
      ,A.ATTRIBUTE14 AS SUBSDR_CD
      ,'*' AS AU_CD
      ,'N' AS MANUAL_ADJ_FLAG
      ,B.KPI_CD AS KPI_CD
      ,'BEP_SMART_PROD_MMGN' AS CAT_CD
      ,A.ATTRIBUTE4 AS SUB_CAT_CD
      ,A.ATTRIBUTE6 AS ZONE_RNR_CD
      ,A.ATTRIBUTE2 AS SUBSDR_RNR_CD
      ,A.ATTRIBUTE8 AS CNTRY_CD
      ,A.ATTRIBUTE1 AS APPLY_YYYYMM
      ,NULL AS CURRM_KRW_AMT
      ,SUM(TO_NUMBER(A.ATTRIBUTE16)) AS CURRM_USD_AMT
      ,NULL AS ACCU_KRW_AMT
      ,NULL AS ACCU_USD_AMT
      ,MIN(ATTRIBUTE13) AS ATTRIBUTE1_VALUE
      ,MIN(ATTRIBUTE2) AS ATTRIBUTE2_VALUE
      ,MIN(ATTRIBUTE4) AS ATTRIBUTE3_VALUE
      ,MIN(ATTRIBUTE6) AS ATTRIBUTE4_VALUE
      ,MIN(ATTRIBUTE8) AS ATTRIBUTE5_VALUE
      ,CURRENT TIMESTAMP AS CREATION_DATE
      ,'ares' AS CREATION_USR_ID
      ,CURRENT TIMESTAMP AS LAST_UPD_DATE
      ,'ares' AS LAST_UPD_USR_ID  
FROM   IPTDW.IPTDW_RES_EXCEL_UPLOAD_DATA A
      ,(
       SELECT 'MARGINAL_PF_(-)' AS KPI_CD FROM   SYSIBM.SYSDUMMY1
       ) B
WHERE  A.SEQ = '1510'
AND    A.CODE_ID = 'BEP_SMART_PROD_MMGN'
AND    A.YYYYMMDD = '201301'
GROUP BY A.ATTRIBUTE1
        ,A.ATTRIBUTE10
        ,A.ATTRIBUTE11
        ,A.ATTRIBUTE14
        ,B.KPI_CD
        ,A.ATTRIBUTE4
        ,A.ATTRIBUTE6
        ,ATTRIBUTE2
        ,ATTRIBUTE8

/*
SQL(1)          : 2097개의 행이 Insert 되었습니다. SQL 소요시간 (0.506)


모든 SQL 실행이 완료되었습니다.
전체 SQL	: 1   SQL 소요시간( 0.506 )

SQL 완료	: 1
*/
