CREATE TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE"  (

		  "BASE_YYYYMM"  VARCHAR(6)  NOT NULL ,   -- 년/월
		  "SUBSDR_CD"    VARCHAR(4)  NOT NULL ,   -- Subsidiary      
		  "SUBSDR_NM"    VARCHAR(30),             -- Subsidiary Name 
		  "DIV_CD"       VARCHAR(3)  NOT NULL ,   -- Division        
		  "DIV_NM"       VARCHAR(50),             -- Division Name
		  "ZOPNO"        VARCHAR(14),             -- Opportunity         
		  "SALE_USD_AMT" DOUBLE ,                 -- Cross Sales Amt(USD)
		  "SALE_KRW_AMT" DOUBLE ,                 -- Cross Sales Amt(KRW)
		  "BU_USD_AMT"   DOUBLE ,                 -- Cross BU Amt(USD)   
		  "BU_KRW_AMT"   DOUBLE ,                 -- Cross BU Amt(KRW)   
		  "SEND_DT"      VARCHAR(10),             -- 전송일자            
		  "SEND_TM"      VARCHAR(10) )            -- 전송시간            
		 DISTRIBUTE BY HASH("BASE_YYYYMM")   
		   IN "TS_STG_D" ; 

COMMENT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" IS 'Cross Sales I/F Table';


-- DDL Statements for primary key on Table "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE"

ALTER TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" 
	ADD CONSTRAINT "IPTDWIF_RES_B2B_CROSSSALE_PK" PRIMARY KEY
		("BASE_YYYYMM",
		 "SUBSDR_CD",
		 "DIV_CD");



-- DDL Statements for indexes on Table "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE"

CREATE INDEX "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE_IX1" ON "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" 
		("DIV_CD" ASC,
		 "SUBSDR_CD" ASC)
		
		COMPRESS YES ALLOW REVERSE SCANS;

--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO ROLE "ROLE_SELECT_ALL" ;

GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "AP68081 " ;

GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "AP72440 " ;

GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "IPT_ISC " ;

GRANT DELETE ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "APPS_IDW" ;

GRANT INSERT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "APPS_IDW" ;

GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "APPS_IDW" ;

GRANT UPDATE ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "APPS_IDW" ;

GRANT DELETE ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "ETL_IDW " ;

GRANT INSERT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "ETL_IDW " ;

GRANT SELECT ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "ETL_IDW " ;

GRANT UPDATE ON TABLE "IPTDWIF"."IPTDWIF_RES_B2B_CROSSSALE" TO USER "ETL_IDW " ;

