-- 1. W5 가장최근
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W5' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME < '20151210'
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 36 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 1. W5 가장최근 - 1
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W5' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 7 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 43 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 1. W5 가장최근 - 2
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W5' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 14 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 50 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 1. W5 가장최근 - 3
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W5' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 21 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 57 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 1. W5 가장최근 - 4
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W5' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 28 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 64 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
UNION ALL
-- 2. W13 가장최근
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W13' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME < '20151210'
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 92 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 2. W13 가장최근 - 1
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W13' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 7 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 99 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 2. W13 가장최근 - 2
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W13' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 14 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 106 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 2. W13 가장최근 - 3
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W13' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 21 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 113 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 2. W13 가장최근 - 4
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W13' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 28 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 120 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
UNION ALL
-- 3. W52 가장최근
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W52' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME < '20151210'
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 365 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 3. W52 가장최근 - 1
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W52' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 7 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 372 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 3. W52 가장최근 - 2
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W52' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 14 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 379 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 3. W52 가장최근 - 3
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W52' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 21 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 386 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
-- 3. W52 가장최근 - 4
UNION ALL
SELECT CASE COPY_T.SEQ
            WHEN '1' THEN 'ALL'
            WHEN '2' THEN A.DIV_CD END AS DIV_CD
      ,MAX(C.BASE_YYYYWW) AS BASE_YYYYWW
      ,'W52' AS KPI_CD
      ,SUM(CASE A.KPI_CD WHEN 'AWARD' THEN A.CURRM_USD_AMT END)
          / SUM(CASE A.KPI_CD WHEN 'SALES' THEN A.CURRM_USD_AMT END)  AS BB_RATIO
FROM   IPTDW.IPTDW_RES_KPI_SUBSDR_CNTRY A
      ,IPTDW.IPTDW_RES_DIM_MST_DIV_PROD_MAPPING B     
      ,(SELECT DISTINCT A.CODE_ID AS BASE_YYYYWW
        FROM   IPTDW.IPTDW_RES_DIM_CODES A
              ,IPTDW.IPTDW_RES_DIM_CODES B
        WHERE  A.CODE_TYPE = 'SMART_WEEK'
        AND    A.CODE_TYPE = B.CODE_TYPE
        AND    A.CODE_NAME <  TO_CHAR(to_date('20151210', 'YYYYMMDD') - 28 DAY, 'YYYYMMDD')
        AND    B.CODE_NAME >= TO_CHAR(to_date('20151210', 'YYYYMMDD') - 393 DAY, 'YYYYMMDD')
        AND    A.CODE_ID   >= B.CODE_ID ) C
      ,(SELECT '1' AS SEQ FROM SYSIBM.SYSDUMMY1 UNION ALL
        SELECT '2' AS SEQ FROM SYSIBM.SYSDUMMY1) COPY_T
WHERE  A.DIV_CD = B.DIVISION_CODE
AND    A.CAT_CD = 'BEP_SMART_BB'
AND    A.SUBSDR_CD = 'EHAP'
AND    A.APPLY_YYYYMM = C.BASE_YYYYWW
GROUP BY CASE COPY_T.SEQ
              WHEN '1' THEN 'ALL'
              WHEN '2' THEN A.DIV_CD END
